//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pivot.Framework.Domain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pivot.Framework.Domain.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already exists !.
        /// </summary>
        internal static string AlreadyExists {
            get {
                return ResourceManager.GetString("AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A non-empty request body is required..
        /// </summary>
        internal static string ANoneEmptyRequestBodyIsRequired {
            get {
                return ResourceManager.GetString("ANoneEmptyRequestBodyIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one is required !.
        /// </summary>
        internal static string AtLeastOneIsRequired {
            get {
                return ResourceManager.GetString("AtLeastOneIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to collection.is.too.large.
        /// </summary>
        internal static string collection_is_too_large {
            get {
                return ResourceManager.GetString("collection.is.too.large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to collection.is.too.small.
        /// </summary>
        internal static string collection_is_too_small {
            get {
                return ResourceManager.GetString("collection.is.too.small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection must contain {0} items or more. It contains {1} items..
        /// </summary>
        internal static string CollectionIsTooLarge {
            get {
                return ResourceManager.GetString("CollectionIsTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection must contain {0} items or more. It contains {1} items..
        /// </summary>
        internal static string CollectionIsToSmall {
            get {
                return ResourceManager.GetString("CollectionIsToSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to currency.
        /// </summary>
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currencies are not the same : {0} !.
        /// </summary>
        internal static string CurrencyMismatch {
            get {
                return ResourceManager.GetString("CurrencyMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email.already.in.use.
        /// </summary>
        internal static string email_already_in_use {
            get {
                return ResourceManager.GetString("email.already.in.use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email.not.found.
        /// </summary>
        internal static string email_not_found {
            get {
                return ResourceManager.GetString("email.not.found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email {0} is already taken !.
        /// </summary>
        internal static string EmailAlreadyInUse {
            get {
                return ResourceManager.GetString("EmailAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email {0} was not found !.
        /// </summary>
        internal static string EmailNotFound {
            get {
                return ResourceManager.GetString("EmailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for field {0}.
        /// </summary>
        internal static string ForField {
            get {
                return ResourceManager.GetString("ForField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for id {0}.
        /// </summary>
        internal static string ForId {
            get {
                return ResourceManager.GetString("ForId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to internal.server.error.
        /// </summary>
        internal static string internal_server_error {
            get {
                return ResourceManager.GetString("internal.server.error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid.string.length.
        /// </summary>
        internal static string invalid_string_length {
            get {
                return ResourceManager.GetString("invalid.string.length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid error serialization.
        /// </summary>
        internal static string InvalidErrorSerialization {
            get {
                return ResourceManager.GetString("InvalidErrorSerialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length{0}is invalid !.
        /// </summary>
        internal static string InvalidLength {
            get {
                return ResourceManager.GetString("InvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to money.
        /// </summary>
        internal static string Money {
            get {
                return ResourceManager.GetString("Money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does not exist !.
        /// </summary>
        internal static string NotExists {
            get {
                return ResourceManager.GetString("NotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is out of range !.
        /// </summary>
        internal static string OutOfRange {
            get {
                return ResourceManager.GetString("OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to record.not.found.
        /// </summary>
        internal static string record_not_found {
            get {
                return ResourceManager.GetString("record.not.found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record not found{0} !.
        /// </summary>
        internal static string RecordNotFound {
            get {
                return ResourceManager.GetString("RecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value{0}is required !.
        /// </summary>
        internal static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown value !.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value already exists.
        /// </summary>
        internal static string value_already_exists {
            get {
                return ResourceManager.GetString("value.already.exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value.is.invalid.
        /// </summary>
        internal static string value_is_invalid {
            get {
                return ResourceManager.GetString("value.is.invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value.is.required.
        /// </summary>
        internal static string value_is_required {
            get {
                return ResourceManager.GetString("value.is.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value.is.tolong.
        /// </summary>
        internal static string value_is_tolong {
            get {
                return ResourceManager.GetString("value.is.tolong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value.is.toshort.
        /// </summary>
        internal static string value_is_toshort {
            get {
                return ResourceManager.GetString("value.is.toshort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value.not.negative.
        /// </summary>
        internal static string value_not_negative {
            get {
                return ResourceManager.GetString("value.not.negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value {0} already exists !.
        /// </summary>
        internal static string ValueAlreadyExists {
            get {
                return ResourceManager.GetString("ValueAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} for {1}.
        /// </summary>
        internal static string ValueForField {
            get {
                return ResourceManager.GetString("ValueForField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value{0}is invalid !.
        /// </summary>
        internal static string ValueIsInvalid {
            get {
                return ResourceManager.GetString("ValueIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value {0} should not be negative !.
        /// </summary>
        internal static string ValueIsNegative {
            get {
                return ResourceManager.GetString("ValueIsNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value{0}is to long, maximum length of {1} is allowed !.
        /// </summary>
        internal static string ValueIsToLong {
            get {
                return ResourceManager.GetString("ValueIsToLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value{0}is to short, minimum length of {1} is required !.
        /// </summary>
        internal static string ValueIsToShort {
            get {
                return ResourceManager.GetString("ValueIsToShort", resourceCulture);
            }
        }
    }
}
